### ISSUE TITLE
17-futures/countries/flags_asyncio.py fails to download flags

### ISSUE THREAD

**Issue by cdm-work** [fluentpython/example-code#25]
When running with python 3.6.6, with aiohttp 3.3.2, the 'flags_asyncio.py' script outputs 20 pairs of lines similar to this:
`Unclosed client session`
`client_session: <aiohttp.client.ClientSession object at 0x10ecbfd68>```
followed by 20 tracebacks similar to this:
```Task exception was never retrieved`
`future: <Task finished coro=<download_one() done, defined at flags_asyncio.py:28>` `exception=TypeError("'_SessionRequestContextManager' object is not iterable",)>`
`Traceback (most recent call last):`
` File "flags_asyncio.py", line 30, in download_one`
`    image = yield from get_flag(cc)  # <7>`
`  File "flags_asyncio.py", line 23, in get_flag`
`    resp = yield from aiohttp.request('GET', url)  # <4>`
`TypeError: '_SessionRequestContextManager' object is not iterable`

**Comment by cdm-work** [comment]
Pull request #26 would address this issue.  Obviously it would be out of sync with the book contents, but it would actually work and produce a positive result.
